id: P004497
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4299
  title: མཁན་རིན་པོ་ཆེ་འཇམ་དཔལ་དོན་བརྒྱུད་ཉི་མའི་མཛད་རྣམ་རགས་བསྡུས་ཙམ་བཀོད་པ་
  author: ''
  volumes:
    76adfc04e64a49a9bd2a3c291dba1cfa:
      image_group_id: I1PD100507
      title: ''
      volume_number: 1
      total_pages: 80
      base_file: v001.txt
